default_platform(:ios)

def clean_fastlane
  sh "rm -rf fastlane/test_output/*.xcresult"
  sh "rm -rf ~/Library/Developer/Xcode/DerivedData"
  sh "rm -rf fastlane/test_output"
  sh "rm -rf fastlane/logs"
end


platform :ios do
  desc "unit test"
  lane :unit_test do
    clean_fastlane

    scan(
      project: "Navigation.xcodeproj",
      scheme: "Navigation",
      testplan: "Navigation",
      clean: true,
      code_coverage: true,
      output_directory: "fastlane/test_output",
      output_types: "junit",
      output_files: "report.junit",
      result_bundle: true,
      result_bundle_path: "fastlane/test_output",
      buildlog_path: "fastlane/logs",
      fail_build: true,
      xcargs: "CODE_SIGNING_ALLOWED=NO -destination 'platform=iOS Simulator,name=iPhone 15' -parallel-testing-enabled YES"
    )
  end


end
